apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pg98w53nk-go
  janus-idp.io/tekton: pg98w53nk-go
  backstage.io/kubernetes-id: pg98w53nk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pg98w53nk-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
