apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pg98w53nk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pg98w53nk-go 
  name: pg98w53nk-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pg98w53nk-go 
